version: '3.9'

volumes:
  pgdata:

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "ads"
      POSTGRES_USER: "ads"
      POSTGRES_PASSWORD: "adsads123"
    ports:
      - "5432:5432"